# services:
#   postgres:
#     image: postgres:15
#     container_name: narwastuconnect_pg
#     restart: always
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:

services:
  app:
    build: .
    container_name: narwastuconnect_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env   # ⬅ ini otomatis load semua variable dari file .env
    # environment:
    #   DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb?sslmode=disable
    ports:
      - "8080:8080" # expose API
    # ✅ bisa juga set env langsung untuk firebase
    environment:
      FIREBASE_SERVICE_ACCOUNT_JSON: "${FIREBASE_SERVICE_ACCOUNT_JSON}"
    
    # kalau local aktifkan
    # volumes:
    #   - ./config/firebase_service_account.json:/app/config/firebase_service_account.json:ro

  postgres:
    image: postgres:15
    container_name: narwastuconnect_pg
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
